name: Checkout and Install

on: workflow_call

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Copy Secrets
        run: sh ./.github/scripts/env.sh

