name: Deploy to Environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to <dev|stage|prod>'
        required: true
        type: string
        default: 'dev'
      # projectId:
      #   description: 'Firebase Project'
      #   required: true
      #   type: string
      #   default: 'barbago-dev'
      runJob:
        description: 'Which jobs to run'
        required: false
        type: string
        default: 'all'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod
        default: 'dev'
      # projectId:
      #   description: 'Firebase Project'
      #   required: true
      #   type: choice
      #   options:
      #     - barbago-dev
      #     - barbago-stage
      #     - barbago-prod
      #   default: 'barbago-dev'
      runJob:
        description: 'Which jobs to run'
        required: false
        type: choice
        options:
          - all
          - api
          - mobile
          - web
        default: 'all'

jobs:
  deploy_web:
    name: Deploy Web
    runs-on: ubuntu-latest
    if: inputs.runJob == 'all' || inputs.runJob == 'web'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Copy Secrets
        run: sh ./.github/scripts/env.sh

      - name: Web Deploy with Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ env.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ env.FIREBASE_ACCOUNT }}'
          projectId: '${{ env.projectId }}'
          channelId: 'live'

  deploy_mobile:
    name: Deploy Expo Go
    runs-on: ubuntu-latest
    if: inputs.runJob == 'all' || inputs.runJob == 'mobile'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        working-directory: ui
        run: npm ci

      - name: Copy Secrets
        run: sh ./.github/scripts/env.sh

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          packager: npm
          token: '${{ env.EXPO_TOKEN }}'

      - name: Mobile Deploy with EAS
        working-directory: ui
        run: eas update --non-interactive --auto --branch '${{ inputs.environment }}'

  deploy_backend:
    name: Deploy Backend API
    runs-on: ubuntu-latest
    if: inputs.runJob == 'all' || inputs.runJob == 'api'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        working-directory: functions
        run: npm ci

      - name: Functions Deploy with Firebase
        run: npx firebase-tools deploy --only functions --token '${{ env.FIREBASE_TOKEN }}' -P '${{ env.projectId }}'

env:
  EXPO_TOKEN: '${{ secrets.EXPO_TOKEN }}'
  FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  # https://github.com/orgs/community/discussions/25725
  ENV_FILE: "${{ inputs.environment == 'prod' && secrets.ENV_FILE_PROD || inputs.environment == 'stage' && secrets.ENV_FILE_STAGE || inputs.environment == 'dev' && secrets.ENV_FILE_DEV || null }}"
  FIREBASE_ACCOUNT: "${{ inputs.environment == 'prod' && secrets.FIREBASE_SERVICE_ACCOUNT_BARBAGO_PROD || inputs.environment == 'stage' && secrets.FIREBASE_SERVICE_ACCOUNT_BARBAGO_STAGE || inputs.environment == 'dev' && secrets.FIREBASE_SERVICE_ACCOUNT_BARBAGO_DEV || null }}"
  projectId: '${{ fromJSON('{"dev": "barbago-dev", "stage": "barbago-stage", "prod": "barbago-prod"}')[inputs.environment] }}'

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
