name: Dev Deploy on commit
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  stage_deploy:
    name: Dev
    uses: ./.github/workflows/deploy.yml
    with:
      environment: develop
    secrets: inherit
