name: Deploy on Push to Main
'on':
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prod_deploy:
    name: Production Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
    secrets: inherit
