name: Deploy on Push to Main
'on':
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prod_deploy:
    name: Prod Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      projectId: barbago-prod
    secrets: inherit
