name: Stage Deploy on Merge
'on':
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  stage_deploy:
    name: Stage
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
    secrets: inherit
