name: Staging Deploy

on:
  workflow_dispatch:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_ui:
    name: Deploy User Interface Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        working-directory: ui
        run: npm ci

      - name: Copy Secrets
        run: sh ./.github/scripts/env.sh

      - name: Web Deploy with Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ env.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ env.FIREBASE_ACCOUNT }}'
          channelId: live
          projectId: '${{ env.FIREBASE_PROJECT }}'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          packager: npm
          token: '${{ env.EXPO_TOKEN }}'

      - name: Mobile Deploy with EAS
        working-directory: ui
        run: eas update --non-interactive --auto

  deploy_backend:
    name: Deploy REST API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        working-directory: functions
        run: npm ci

      - name: Firebase Deploy
        run: npx firebase-tools deploy --only functions --token '${{ env.FIREBASE_ACCOUNT }}' -P '${{ env.FIREBASE_PROJECT }}'


env:
  ENV_FILE: '${{secrets.ENV_FILE_STAGE}}'
  EXPO_TOKEN: '${{ secrets.EXPO_TOKEN }}'
  FIREBASE_ACCOUNT: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BARBAGO_STAGE }}'
  FIREBASE_PROJECT: 'barbago-stage'
  FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
