name: Stage Deploy on Release
'on':
  push:
    branches:
      - release/**

jobs:
  stage_deploy:
    name: Stage
    uses: ./.github/workflows/deploy.yml
    with:
      environment: stage
    secrets: inherit
